shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
hooks.post = "autoload -Uz compinit && compinit"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
